language: java
sude: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "heckenmann-github"
    token:
      secure: "Au1GeGCkV5sDMjMCFuaLpZ8ALD8kajjc1A1nDCzHx+OEMCeBzEP0ad/O0uC3encrixMd/2eAhPJHZd1i2Pf61b4LhJt/5gvcBPA7+UgHFWyLcaQYzyMqZbYkXRa5GB/SEuL3yfbAVifCNZRta2sOXmDDAqqecFD6KYvPI9GT/crVkEJoopxwXL/v0LcSzA1Bv1ckc3tH/3mTgrTeZ6ySsy0K74hJxFKR6KgPY2o7vmAwNm9M1b9lkg/7d2xWNPo2XPH9YLX1HI9XNnB0F9QLb7WmQVVsnUEfrUMZOEG9xTPOENZySkutbpUJY5wjseOhmcPYr+6jhszVbJ7UC7o5bDJgkf1itvf4OgrvcMtqjhnIKPfJ58lyR4V+PeuZ2mvIUjoYFTH6FKaleDLCM5iFSdajLRlLTD/La/gwqO9A4AuwF6ZL8SMNN4asE32sWK7iB9jeuwf90PmMYNeQidE1gKBy120mjKFd5J9yznwFJjlZkP7XV8u/mcXeAL2M8d8QZChboiM4fbHlnPFJZ5hptf02AkGNZ8OedjZRhHR50Ji3hCTLa5GoCK9fUdw2fHZK0+8BSRdlI65/kUOmh3oTHC4aObj9ClDq9kcYAVex2Y93ScwWNVAiM5auwDsZEIwey4RfRSUhJJNG9M5NWx7g/AHZyffV94SoT1D5qLuXkXU="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests=true
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
