language: java
sude: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "heckenmann-github"
    token: "$sonarcloud-token"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests=true
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
