language: java
sude: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "heckenmann-github"
    token:
      secure: "pfXuoEJoBLasLj+WxZACkxnfM9aY4+fOfj5sKy9j+tOYG24+JjHYPSZnC2s11mEjAT5iJC+lwMJbSOPw5auRbQ1Fj0Jzn6nExe62ANULMHTgxEAHNksE1Y+XldKr6OvsvG3evNjl8VG41dYr5mGRUz2kxKzp17vsXdqw9npV5q41TJI1jxKdoLM3k+5YgMVXjNFWSQbtEC8pJ1+FuzGa6jYBzvivqQAWPLQ/MzrZ62RG3H5dZrzL0v6qgCf+hqkxxXtDIWj0g4gk4pLlXHV13ROjFgwCc2Gi05b3n5nvWC/xeEe9R4/QautSf8fbB2qpx2qVeTLQhbSpIku5zW7/HjIb9CBAFd+LJXnnxA4rMGPvfrxEEfdOQxerotdf7Pz9FneYZjNEt5OHOwSBygBp000Z9R6RZQ8NPZHYAf8kQC2scxBd9oRTy5MZYYsYieeMbeJnMN9yKfm4NuqdoQ6ICy72aahCQ70WT6r0lUJYNDdFyIsKgK0qNR+l5mWMh0GuEk2ALDx7olXcGDpvRhyuHpEaqZxPV75KxnrwyfRPhHkOxfRrqUWj4QfgVii3vld7+GT3tzeodtPF+lD1qbbPtupRCne0Mh9F/AHflBPbN8h2iOuUEkUClKWwFwJfVToD5PKXlQc2jR4hhLfonadVRIeovI1JvkBrjjbVn488mPU="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -DskipTests=true
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
